import { HttpClient } from '@angular/common/http';
import { Injectable, inject } from '@angular/core';
import { generateRandomString } from '@app/auth/code-verifier';
import { environment } from '@env/environment';
import { Observable, map } from 'rxjs';

@Injectable({
  providedIn: 'root',
})
export class AuthService {
  private _httpClient = inject(HttpClient);

  /**
   * Fetch an access token from the Spotify API.
   * Does not link to a certain user,
   * so it can only be used to fetch public data.
   */
  getClientToken$(): Observable<SpotifyClientToken> {
    const headers = { 'Content-Type': 'application/x-www-form-urlencoded' };
    const body = new URLSearchParams({
      client_id: environment.spotifyClientId,
      client_secret: environment.spotifyClientSecret,
      grant_type: 'client_credentials',
    });
    return this._httpClient
      .post<SpotifyClientTokenResponse>(
        `${environment.authApi}api/token`,
        body.toString(),
        { headers }
      )
      .pipe(map(mapClientToken));
  }

  /**
   * fetch an access token from the Spotify API.
   * This token is linked to a certain user,
   * so it can be used to fetch private data.
   * @param authorizationCode The authorization code that was returned from the Spotify API.
   * @returns An observable that emits the access token.
   */
  getAuthorizationToken$(
    authorizationCode: string,
    codeVerifier: string
  ): Observable<SpotifyAuthenticationToken> {
    const headers = {
      'Content-Type': 'application/x-www-form-urlencoded',
    };
    const body = new URLSearchParams({
      client_id: environment.spotifyClientId,
      code_verifier: codeVerifier,
      code: authorizationCode,
      grant_type: 'authorization_code',
      redirect_uri: environment.redirectUrl,
      scope: 'user-top-read',
    });
    return this._httpClient
      .post<SpotifyAuthenticationTokenResponse>(
        `${environment.authApi}api/token`,
        body.toString(),
        { headers }
      )
      .pipe(map(mapAuthenticationToken));
  }

  /**
   * refresh an access token from the Spotify API.
   * This token is linked to a certain user,
   * so it can be used to fetch private data.
   * @param refreshToken The refresh toke, that was returned from the Spotify API.
   * @returns An observable that emits the access token.
   */
  refreshAuthorizationToken$(
    refreshToken: string
  ): Observable<SpotifyAuthenticationToken> {
    const headers = {
      'Content-Type': 'application/x-www-form-urlencoded',
    };
    const body = new URLSearchParams({
      client_id: environment.spotifyClientId,
      grant_type: 'refresh_token',
      refresh_token: refreshToken,
    });
    return this._httpClient
      .post<SpotifyAuthenticationTokenResponse>(
        `${environment.authApi}api/token`,
        body.toString(),
        { headers }
      )
      .pipe(map(mapAuthenticationToken));
  }

  /**
   * Authenticates the user using PKCE flow.
   * @param codeChallenge The code challenge generated by the client.
   */
  async pkceAuthenticate(codeChallenge: string) {
    const clientId = environment.spotifyClientId;
    const redirectUri = environment.redirectUrl;

    const url = new URL(`${environment.authApi}authorize`);
    const params = {
      response_type: 'code',
      client_id: clientId,
      code_challenge_method: 'S256',
      code_challenge: codeChallenge,
      redirect_uri: redirectUri,
      state: generateRandomString(16),
    };
    url.search = new URLSearchParams(params).toString();
    window.location.href = url.toString();
  }
}

export type SpotifyAccessToken =
  | SpotifyClientToken
  | SpotifyAuthenticationToken;

export type SpotifyClientToken = {
  accessToken: string;
  expiryDate: number;
  tokenType: 'Bearer';
};

export type SpotifyAuthenticationToken = SpotifyClientToken & {
  refreshToken: string;
};

export function isSpotifyAuthenticationToken(
  accesToken: SpotifyAccessToken
): accesToken is SpotifyAuthenticationToken {
  return !!(accesToken as SpotifyAuthenticationToken).refreshToken;
}

type SpotifyClientTokenResponse = {
  access_token: string;
  token_type: 'Bearer';
  expires_in: number;
};

type SpotifyAuthenticationTokenResponse = SpotifyClientTokenResponse & {
  refresh_token: string;
};

function mapAuthenticationToken(
  tokenResponse: SpotifyAuthenticationTokenResponse
): SpotifyAuthenticationToken {
  return {
    ...mapClientToken(tokenResponse),
    refreshToken: tokenResponse.refresh_token,
  };
}

function mapClientToken(
  tokenResponse: SpotifyClientTokenResponse
): SpotifyClientToken {
  return {
    accessToken: tokenResponse.access_token,
    tokenType: tokenResponse.token_type,
    expiryDate: Date.now() + tokenResponse.expires_in * 1_000,
  };
}
