import { HttpClient } from '@angular/common/http';
import { Injectable, inject } from '@angular/core';
import { generateRandomString } from '@app/auth/code-verifier';
import { environment } from '@env/environment';
import { Observable } from 'rxjs';

@Injectable({
  providedIn: 'root',
})
export class AuthService {
  private _httpClient = inject(HttpClient);

  /**
   * Fetch an access token from the Spotify API.
   * Does not link to a certain user,
   * so it can only be used to fetch public data.
   */
  getClientToken$(): Observable<SpotifyAccesTokenResponse> {
    const headers = { 'Content-Type': 'application/x-www-form-urlencoded' };
    const body = new URLSearchParams({
      client_id: environment.spotifyClientId,
      client_secret: environment.spotifyClientSecret,
      grant_type: 'client_credentials',
    });
    return this._httpClient.post<SpotifyAccesTokenResponse>(
      `${environment.authApi}api/token`,
      body.toString(),
      { headers }
    );
  }

  /**
   * fetch an access token from the Spotify API.
   * This token is linked to a certain user,
   * so it can be used to fetch private data.
   * @param authorizationCode The authorization code that was returned from the Spotify API.
   * @returns An observable that emits the access token.
   */
  getAuthorizationToken$(
    authorizationCode: string,
    codeVerifier: string
  ): Observable<SpotifyUserAccessTokenResponse> {
    const headers = {
      'Content-Type': 'application/x-www-form-urlencoded',
    };
    const body = new URLSearchParams({
      client_id: environment.spotifyClientId,
      code_verifier: codeVerifier,
      code: authorizationCode,
      grant_type: 'authorization_code',
      redirect_uri: environment.redirectUrl,
    });
    return this._httpClient.post<SpotifyUserAccessTokenResponse>(
      `${environment.authApi}api/token`,
      body.toString(),
      { headers }
    );
  }

  /**
   * refresh an access token from the Spotify API.
   * This token is linked to a certain user,
   * so it can be used to fetch private data.
   * @param refreshToken The refresh toke, that was returned from the Spotify API.
   * @returns An observable that emits the access token.
   */
  refreshAuthorizationToken$(
    refreshToken: string
  ): Observable<SpotifyUserAccessTokenResponse> {
    const headers = {
      'Content-Type': 'application/x-www-form-urlencoded',
    };
    const body = new URLSearchParams({
      client_id: environment.spotifyClientId,
      grant_type: 'refresh_token',
      refresh_token: refreshToken,
    });
    return this._httpClient.post<SpotifyUserAccessTokenResponse>(
      `${environment.authApi}api/token`,
      body.toString(),
      { headers }
    );
  }

  /**
   * Authenticates the user using PKCE flow.
   * @param codeChallenge The code challenge generated by the client.
   */
  async pkceAuthenticate(codeChallenge: string) {
    const clientId = environment.spotifyClientId;
    const redirectUri = environment.redirectUrl;

    const url = new URL(`${environment.authApi}authorize`);
    const params = {
      response_type: 'code',
      client_id: clientId,
      code_challenge_method: 'S256',
      code_challenge: codeChallenge,
      redirect_uri: redirectUri,
      state: generateRandomString(16),
    };
    url.search = new URLSearchParams(params).toString();
    window.location.href = url.toString();
  }
}

export type SpotifyAccesTokenResponse = {
  access_token: string;
  token_type: 'Bearer';
  expires_in: number;
};

export type SpotifyUserAccessTokenResponse = SpotifyAccesTokenResponse & {
  refresh_token: string;
};
