name: run-tests
run-name: Test with Angular CLI
on: [push]
jobs:
  test with Angular CLI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
        run_install: |
          - recursive: true
            args: [--frozen-lockfile, --strict-peer-dependencies]
          - args: [--global, @angular/cli@17.0.0-rc.1]
      - run: ng test
